import actionsData from '../data/actions.json' with { type: 'json' };
import { MELBOURNE_CBD, haversineMetres, formatDistance } from './geoUtils.js';
import type {
  ActionItem,
  CouncilMatch,
  DevelopmentType,
  GeocodeResult,
  GtpRequest,
  TargetItem,
  TransportSummary,
} from './types.js';

const DEV_TYPE_LABELS: Record<DevelopmentType, string> = {
  residential: 'residential (dwellings)',
  mixedUse: 'mixed-use (residential + commercial)',
  commercialOffice: 'commercial office',
  retail: 'retail',
  education: 'education',
  industrial: 'industrial / warehouse',
};

export interface GtpContent {
  meta: {
    address: string;
    developmentType: DevelopmentType;
    developmentTypeLabel: string;
    scale: string;
    siteDescription: string;
    clientName: string;
    projectReference: string;
    generatedDate: string;
    council: { id: string; name: string; profileDepth: string };
    matchConfidence: string;
    matchedLgaName?: string;
    dataSources: { geocode: string; transport: string };
  };
  draftBanner: string;
  sourcesOfInformation: string[];
  summary: string;
  introduction: string;
  gtpIntro: string;
  subjectSiteNarrative: string;
  transportNarrative: string;
  transport: TransportSummary;
  policyNarrative: string;
  targets: TargetItem[];
  actionsByCategory: Record<string, ActionItem[]>;
  monitoringAndReporting: string;
}

function buildSummary(req: GtpRequest, typeLabel: string, councilName: string): string {
  return (
    `The proposed ${typeLabel} development at ${req.address} is to adopt strategies that promote the use of ` +
    `public transport, reduce reliance on private motor vehicles, and encourage sustainable travel modes such ` +
    `as walking, cycling and shared vehicles. These strategies aim to minimise the environmental impacts ` +
    `associated with transport-related activity generated by the development` +
    (req.scale ? ` (${req.scale})` : '') +
    `, and are tuned to the transport priorities published by ${councilName}.`
  );
}

function buildIntroduction(req: GtpRequest, councilName: string): string {
  return (
    `This Green Travel Plan (GTP) responds to the proposed development at ${req.address} and sets out suitable ` +
    `infrastructure and measures to promote sustainable travel. The transport sector remains one of Victoria's ` +
    `largest sources of greenhouse gas emissions, and the Victorian Government together with local councils, ` +
    `including ${councilName}, require a strategic green and sustainable transport plan for new developments ` +
    `of this nature.\n\nThe aim of this GTP is to minimise the environmental impacts associated with commuting ` +
    `to and from the development, structured around three objectives: reduce reliance on private motor ` +
    `vehicles; promote the use of public transport; and encourage walking, cycling and shared vehicles.`
  );
}

function buildSubjectSiteNarrative(req: GtpRequest, geocode: GeocodeResult, typeLabel: string): string {
  const distCbd = haversineMetres(geocode, MELBOURNE_CBD);
  return (
    `The site is located at ${req.address}${geocode.suburb ? `, ${geocode.suburb}` : ''}${
      geocode.postcode ? ` ${geocode.postcode}` : ''
    }. The proposed development is ${typeLabel}${req.scale ? ` (${req.scale})` : ''}.` +
    (req.siteDescription ? ` ${req.siteDescription}` : '') +
    ` The site is located approximately ${formatDistance(distCbd)} from Melbourne CBD.`
  );
}

function joinStops(items: TransportSummary['train'], radiusM: number, label: string): string {
  if (!items.length) return `None identified within ${radiusM}m — confirm manually.`;
  return items.map((s) => s.name).join('\n');
}

function joinDistances(items: TransportSummary['train']): string {
  if (!items.length) return '-';
  return items.map((s) => `${s.distanceLabel}, ~${s.walkMinutes} min`).join('\n');
}

function buildTransportNarrative(transport: TransportSummary): string {
  const nearest = (arr: TransportSummary['train'], label: string) =>
    arr.length
      ? arr.map((s) => `${s.name} (${s.distanceLabel}, ~${s.walkMinutes} min walk)`).join('; ')
      : `No ${label} identified within the ${transport.searchRadiusM}m search radius — confirm manually.`;

  const errorNote = transport._error ? `\n\nNote: ${transport._error}` : '';

  return (
    `Public Transport: ${nearest(transport.train, 'train station')}. Tram: ${nearest(transport.tram, 'tram stop')}. ` +
    `Bus: ${nearest(transport.bus, 'bus stop')}.\n\nCar Share: ${nearest(transport.carShare, 'car share pod')}.\n\n` +
    `Cycling Infrastructure: ${transport.cyclingInfraCount} mapped cycling-related way(s) within ${transport.searchRadiusM}m ` +
    `(OpenStreetMap).${errorNote}`
  );
}

function buildPolicyNarrative(council: CouncilMatch): string {
  const { council: c, matchConfidence } = council;
  const confidenceNote =
    matchConfidence === 'lga-matched-no-detailed-profile'
      ? `\n\nNote: this address is in ${council.matchedLgaName}, which does not yet have a detailed profile in this ` +
        `tool — the generic, state-wide policy themes below are used as a starting point and should be replaced with ` +
        `council-specific research before this GTP is finalised.`
      : matchConfidence === 'no-match-generic-fallback'
        ? ` Note: this address could not be matched to a Victorian council boundary — the generic, state-wide policy ` +
          `themes below are used as a starting point and should be verified manually before this GTP is finalised.`
        : '';

  const priorities = c.strategicPriorities.length
    ? '\n\nStrategic priorities:\n' + c.strategicPriorities.map((p) => `- ${p}`).join('\n')
    : '';
  const sources = c.sourceDocuments.length
    ? '\n\nSource documents:\n' + c.sourceDocuments.map((d) => `- ${d.title} (${d.url})`).join('\n')
    : '';

  return `${c.visionStatement}\n\n${c.policyNarrative}${confidenceNote}${priorities}${sources}`;
}

function buildTargets(council: CouncilMatch): TargetItem[] {
  const targets: TargetItem[] = [];
  if (council.council.profileDepth === 'detailed') {
    for (const t of council.council.quantifiedTargets) {
      targets.push({ text: t, source: `${council.council.name} published target`, sourced: true });
    }
  }
  targets.push({
    text:
      'Reduce the number of trips to/from the site by single-occupant private vehicle for work purposes ' +
      '(indicative target: 20-30% reduction against a no-GTP baseline — confirm with Council/traffic engineer).',
    source: 'Industry-benchmark placeholder — not council-sourced',
    sourced: false,
  });
  targets.push({
    text:
      'Increase use of public transport by occupants/visitors (indicative target: at least 30-40% of trips — ' +
      'align to local mode-share data where available).',
    source: 'Industry-benchmark placeholder — not council-sourced',
    sourced: false,
  });
  targets.push({
    text: 'Increase use of walking, cycling and shared vehicles by occupants/visitors (indicative target: at least 20-30% of trips).',
    source: 'Industry-benchmark placeholder — not council-sourced',
    sourced: false,
  });
  return targets;
}

function buildActionsByCategory(council: CouncilMatch): Record<string, ActionItem[]> {
  const weights = council.council.actionWeights || {};
  const byCategory: Record<string, ActionItem[]> = {};
  for (const a of actionsData.actions as Array<{ category: string; text: string; weight: number }>) {
    if (!byCategory[a.category]) byCategory[a.category] = [];
    const councilWeight = weights[a.category] ?? 1.0;
    byCategory[a.category].push({ category: a.category, text: a.text, score: a.weight * councilWeight, priority: false });
  }
  for (const cat of Object.keys(byCategory)) {
    byCategory[cat].sort((a, b) => b.score - a.score);
    byCategory[cat].forEach((item, idx) => {
      item.priority = idx < 3 && item.score >= 2;
    });
  }
  return byCategory;
}

export function generateGtpContent(
  req: GtpRequest,
  geocode: GeocodeResult,
  councilMatch: CouncilMatch,
  transport: TransportSummary
): GtpContent {
  const typeLabel = DEV_TYPE_LABELS[req.developmentType] || req.developmentType;
  const councilName = councilMatch.council.name;

  return {
    meta: {
      address: req.address,
      developmentType: req.developmentType,
      developmentTypeLabel: typeLabel,
      scale: req.scale || '',
      siteDescription: req.siteDescription || '',
      clientName: req.clientName || '',
      projectReference: req.projectReference || '',
      generatedDate: new Date().toISOString().slice(0, 10),
      council: { id: councilMatch.council.id, name: councilName, profileDepth: councilMatch.council.profileDepth },
      matchConfidence: councilMatch.matchConfidence,
      matchedLgaName: councilMatch.matchedLgaName,
      dataSources: { geocode: geocode._source, transport: transport._source },
    },
    draftBanner:
      'AUTOMATICALLY GENERATED DRAFT — this document was produced by GIW’s GTP generator from address-level ' +
      'open data and published council transport-strategy documents. It has not been checked by a qualified ' +
      'consultant. Verify every figure, clause reference and target before issuing to a client or council.',
    sourcesOfInformation: [
      'Site address and development brief as supplied',
      'OpenStreetMap (Nominatim geocoding, Overpass transport/cycling data)',
      ...councilMatch.council.sourceDocuments.map((d) => `${d.title} (${d.url})`),
      'Victoria Planning Provisions — Clause 18 (Transport)',
    ],
    summary: buildSummary(req, typeLabel, councilName),
    introduction: buildIntroduction(req, councilName),
    gtpIntro:
      'The development is to implement the GTP provided by GIW, which sets measurable targets and actions to be ' +
      'incorporated at design and operational stages, with monitoring and reporting frameworks to track impact.',
    subjectSiteNarrative: buildSubjectSiteNarrative(req, geocode, typeLabel),
    transportNarrative: buildTransportNarrative(transport),
    transport,
    policyNarrative: buildPolicyNarrative(councilMatch),
    targets: buildTargets(councilMatch),
    actionsByCategory: buildActionsByCategory(councilMatch),
    monitoringAndReporting:
      'Effective implementation of this GTP requires monitoring and annual review. An Employee/Occupant Commute ' +
      'Survey (see Appendix A) should be distributed biannually to track mode share and identify further ' +
      'opportunities for improvement, with results reported against the targets above.',
  };
}

export { DEV_TYPE_LABELS, joinStops, joinDistances, buildActionsByCategory };
